### ISSUE TITLE
IE9 and Placeholder

### ISSUE THREAD

**Issue by eungyu** [eungyu/paragraph#23]
IE9 should have placeholder labels displayed. This requires a jQuery plugin or some custom code.

**Comment by suchanlee** [comment]
If there already is a jQuery dependency, https://github.com/mathiasbynens/jquery-placeholder/blob/master/jquery.placeholder.min.js looks like a good choice? 2.66kb minified

**Comment by eungyu** [comment]
The plugin seems like a natural choice. I like the use of html attribute ```placeholder```.

**Comment by eungyu** [comment]
Fixed by 8a3ec12ea0e904b82778b06655dfe900fe3496dc
