### ISSUE TITLE
Support timezones in frontend template

### ISSUE THREAD

**Issue by suchanlee** [eungyu/paragraph#32]
Currently just uses the datetime stored (UTC). Something like "Just posted..." would also be cool?

**Comment by eungyu** [comment]
Good idea, pretty date format would be a nice to have.

**Comment by suchanlee** [comment]
I think that this would be a good little assignment for me to do to and get familiar with paragraph. How can I assign this to myself?

**Comment by eungyu** [comment]
Sweet, that will be really awesome. I have just added you as a contributor. Thanks a lot, and let's have fun.

**Comment by suchanlee** [comment]
yay!

**Comment by suchanlee** [comment]
I did not read the code clearly last time. The timezones are in fact respected. Prettyprinting seems unnecessary at the moment -- closing ticket. Sorry for the confusion!

**Comment by eungyu** [comment]
I was just storing epoch timestamps. I guess ```new Date()``` from Javascript uses local time.

**Comment by suchanlee** [comment]
Yep it uses the local time of the client browser based on epoch datetime.
