### ISSUE TITLE
index.html (used for example) should pull in latest js version

### ISSUE THREAD

**Issue by suchanlee** [eungyu/paragraph#35]
Perhaps it should depend on just paragraph-fat.min.js instead of paragraph-fat-0.x.y.min.js because it's a hassle to keep this version in sync with the project version number. For example, it currently is out-of-sync and the example file does not work out of the box and requires changing the js dependency name.

**Comment by suchanlee** [comment]
@eungyu What are your thoughts on this? If we do keep it versioned, then there should be an established way to keep it in sync with every version change.

**Comment by eungyu** [comment]
I actually think versioned js file is still needed for two reasons
+ browser cache is refreshed as version bumps up
+ users will have clear understanding about bug fixes, etc

So let's keep the versioned js.
I think we can make index.html as Jinja template and substitute js version ```x.y``` as part of grunt compilation

**Comment by suchanlee** [comment]
That makes perfect sense, sounds good.

**Comment by suchanlee** [comment]
What are your thoughts about this? https://github.com/eungyu/paragraph/commit/fc5d458ada76a5f17e1c6e4ce4d148fe80b5af43

It replaces a placeholder path ``/static/js/paragraph-fat.min.js`` with ``/static/js/paragraph-fat-<version>.min.js`` at Grunt compile-time, with the grunt-string-replace library.
