### ISSUE TITLE
Convert and structure front-end code with Browserify

### ISSUE THREAD

**Issue by eungyu** [eungyu/paragraph#38]
See if Asynchronous Module Definition (AMD) makes sense for the project.

**Comment by suchanlee** [comment]
We should use Browerify. It's really great, and it also helps that all React docs also show React and Browerify in action.



—

**Comment by suchanlee** [comment]
I could convert the project to use Browerify tonight and send a PR for evaluation?



—

**Comment by suchanlee** [comment]
Oops. Browserify**



—

**Comment by eungyu** [comment]
that will be perfect!

Sent from my iPhone

On Feb 20, 2015, at 7:15 PM, Suchan Lee <notifications@github.com> wrote:

I could convert the project to use Browerify tonight and send a PR for
evaluation?



—
Sent from Mailbox

On Fri, Feb 20, 2015 at 7:14 PM, Suchan Lee <lee.suchan@gmail.com> wrote:

> We should use Browerify. It's really great, and it also helps that all
React docs also show React and Browerify in action.
> —
> Sent from Mailbox
> On Fri, Feb 20, 2015 at 7:10 PM, Eun-Gyu Kim <notifications@github.com>
> wrote:
>> See if Asynchronous Module Definition (AMD) makes sense for the project.
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/eungyu/paragraph/issues/38

—
Reply to this email directly or view it on GitHub
<https://github.com/eungyu/paragraph/issues/38#issuecomment-75353086>.

**Comment by suchanlee** [comment]
I actually used requirejs but found that there was too much code bloat and made it difficult to manage, so I converted to Browserify and haven't looked back since!



—

**Comment by eungyu** [comment]
Neat, I actually haven't looked into Browserify. It will be a great
learning experience for me!

Sent from my iPhone

On Feb 20, 2015, at 7:18 PM, Suchan Lee <notifications@github.com> wrote:

I actually used requirejs but found that there was too much code bloat and
made it difficult to manage, so I converted to Browserify and haven't
looked back since!



—
Sent from Mailbox

On Fri, Feb 20, 2015 at 7:16 PM, Eun-Gyu Kim <notifications@github.com>
wrote:

> that will be perfect!
> Sent from my iPhone
> On Feb 20, 2015, at 7:15 PM, Suchan Lee <notifications@github.com> wrote:
> I could convert the project to use Browerify tonight and send a PR for
> evaluation?
> —
> Sent from Mailbox
> On Fri, Feb 20, 2015 at 7:14 PM, Suchan Lee <lee.suchan@gmail.com> wrote:
>> We should use Browerify. It's really great, and it also helps that all
> React docs also show React and Browerify in action.
>> —
>> Sent from Mailbox
>> On Fri, Feb 20, 2015 at 7:10 PM, Eun-Gyu Kim <notifications@github.com>
>> wrote:
>>> See if Asynchronous Module Definition (AMD) makes sense for the project.
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/eungyu/paragraph/issues/38
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eungyu/paragraph/issues/38#issuecomment-75353086>.
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/eungyu/paragraph/issues/38#issuecomment-75353107

—
Reply to this email directly or view it on GitHub
<https://github.com/eungyu/paragraph/issues/38#issuecomment-75353179>.

**Comment by suchanlee** [comment]
This PR refactors existing code to use Browserify for front-end dependency: https://github.com/eungyu/paragraph/pull/39

I'll close this ticket out and create a new ticket for updating the README with required information.
