### ISSUE TITLE
Migrate Away from Datastore API

### ISSUE THREAD

**Issue by eungyu** [eungyu/paragraph#45]
WTF, Dropbox just made an announcement they will be deprecating datastore API.
https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/

Need to migrate off of Datastore API (RIP, we had a good run!)
Alternative is to use Dropbox API v2

**Comment by suchanlee** [comment]
Catastrophic! D:
We can move to Dropbox API v2, but that won't be available for a while.

It may sound weird... but do you think that moving to a traditional DB, like SQLite, is an option?

Users who would self host Paragraph are those who are at least somewhat technically competent and using a traditional DB should be okay. Also, with a DB, there are perf gains. Not sure how you envision this project to grow, but imho, one great option is to kind of be like Wordpress, which can either be self-hosted or be used as as service. In this case, I would envision the service would be similar to Disqus, but have it such that the comments can always be downloaded by the user and is always the user's property.

**Comment by eungyu** [comment]
Out of shell-shock now. Able to think clearly.
Now that look back and think about it, I guess the reasons I chose Dropbox for Paragraph are mainly:

+ Giving user the ownership of data
+ Also, not storing any user data should this become a service

I just want to be a bridge-maker between the user and whatever the storage mechanism is (in this case Dropbox). Hosting is good, managing data is painful and time consuming.

The takeaway here, I think, is that you cannot trust any company to be a benevolent angel, given they are free to do whatever they want. I will see what v2 has to offer.
